PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Models/PropiedadAlquiler.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB
{
    public class PropiedadAlquiler : Propiedad
    {
        [Display(Name = "Cantidad de meses:")]
        public int CantMeses { get; set; }

        public override string Contrato()
        {
            if(usuario != null) {
                return "La persona " + usuario.Nombre + " " + usuario.Apellido + " con E-mail: " + usuario.Email + " ha alquilado esta propiedad";
            }
            else
            {
                return "";
            }
            
        }


        
    }
}

PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Controllers/PropiedadAlquilerController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.Context;
using PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.Models;


namespace PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.Controllers
{
    public class PropiedadAlquilerController : Controller
    {
        private readonly InmobiliariaDatabaseContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PropiedadAlquilerController(InmobiliariaDatabaseContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: PropiedadAlquiler
        public async Task<IActionResult> Index()
        {
            return View(await _context.PropiedadAlquiler.Include(x=>x.usuario).ToListAsync());
        }

        // GET: PropiedadAlquiler/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var propiedadAlquiler = await _context.PropiedadAlquiler.Include(x => x.usuario)
                .FirstOrDefaultAsync(m => m.IdPropiedad == id);
            if (propiedadAlquiler == null)
            {
                return NotFound();
            }

            return View(propiedadAlquiler);
        }

        // GET: PropiedadAlquiler/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PropiedadAlquiler/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CantMeses,IdPropiedad,Descripcion,Precio,FotoPropiedad,Tipo")] PropiedadAlquiler propiedadAlquiler)
        {
            if (ModelState.IsValid)
            {
                if (propiedadAlquiler.FotoPropiedad != null)
                {
                    string folder = "images/prop_alquiler/";
                    folder += Guid.NewGuid().ToString() + "_" + propiedadAlquiler.FotoPropiedad.FileName;

                    propiedadAlquiler.FotoPropiedadUrl = "/" + folder;

                    string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);

                    await propiedadAlquiler.FotoPropiedad.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                }
                _context.Add(propiedadAlquiler);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(propiedadAlquiler);
        }


        // GET: PropiedadAlquiler/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var propiedadAlquiler = await _context.PropiedadAlquiler.FindAsync(id);
            if (propiedadAlquiler == null)
            {
                return NotFound();
            }
            return View(propiedadAlquiler);
        }

        // POST: PropiedadAlquiler/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CantMeses,IdPropiedad,Descripcion,Precio,FotoPropiedad,Tipo")] PropiedadAlquiler propiedadAlquiler)
        {
            if (id != propiedadAlquiler.IdPropiedad)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (propiedadAlquiler.FotoPropiedad != null)
                    {
                        string folder = "images/prop_alquiler/";
                        folder += Guid.NewGuid().ToString() + "_" + propiedadAlquiler.FotoPropiedad.FileName;

                        propiedadAlquiler.FotoPropiedadUrl = "/" + folder;

                        string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);

                        await propiedadAlquiler.FotoPropiedad.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                    }
                    _context.Update(propiedadAlquiler);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PropiedadAlquilerExists(propiedadAlquiler.IdPropiedad))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(propiedadAlquiler);
        }

        // GET: PropiedadAlquiler/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var propiedadAlquiler = await _context.PropiedadAlquiler
                .FirstOrDefaultAsync(m => m.IdPropiedad == id);
            if (propiedadAlquiler == null)
            {
                return NotFound();
            }

            return View(propiedadAlquiler);
        }

        // POST: PropiedadAlquiler/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var propiedadAlquiler = await _context.PropiedadAlquiler.FindAsync(id);
            _context.PropiedadAlquiler.Remove(propiedadAlquiler);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PropiedadAlquilerExists(int id)
        {
            return _context.PropiedadAlquiler.Any(e => e.IdPropiedad == id);
        }

        // GET: PropiedadAlquiler/Alquilar/5
        public async Task<IActionResult> Alquilar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.ListaUsuarios = await _context.Usuarios.ToListAsync();

            var propiedadAlquiler = await _context.PropiedadAlquiler.FindAsync(id);
            if (propiedadAlquiler == null)
            {
                return NotFound();
            }
            return View(propiedadAlquiler);
        }

        // POST: PropiedadAlquiler/Alquilar/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Alquilar(PropiedadVenta model)
        {
            PropiedadAlquiler propiedadAlquiler = _context.PropiedadAlquiler.SingleOrDefault(b => b.IdPropiedad == model.IdPropiedad);

            if (propiedadAlquiler == null)
            {
                return NotFound();
            }

            Usuario usuarioDB = _context.Usuarios.SingleOrDefault(b => b.IdUsuario == model.usuario.IdUsuario);

            if (usuarioDB == null)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            //{
                try
                {
                    propiedadAlquiler.usuario = usuarioDB;
                    _context.Update(propiedadAlquiler);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PropiedadAlquilerExists(propiedadAlquiler.IdPropiedad))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

            return View("Details",propiedadAlquiler);
        }

    }
}

PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Views/PropiedadAlquiler/Alquilar.cshtml
@model PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadVenta

@{
    ViewData["Title"] = "Alquilar";
}

<div>
    <h4>Propiedad a Alquilar</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CantMeses)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CantMeses)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dd class="card" style="width: 18rem;">
            <img class="img-fluid img-thumbnail" src="@Model.FotoPropiedadUrl" />
        </dd>
       
    </dl>
</div>

<div class="col-md-4">   
        <form method="post" enctype="multipart/form-data" asp-action="Alquilar" asp-controller="PropiedadAlquiler">

            <div class="row">
                <div class="col-sm-2">
                    @Html.DisplayNameFor(model => model.usuario)
                </div>
                <select asp-for="usuario.IdUsuario" class="form-control" asp-items="@(new SelectList(ViewBag.ListaUsuarios,"IdUsuario", "Nombre"))">
                    <option selected="selected" value="">Seleccione</option>
                </select>
            </div>
            <br>
            <div class="row">
                <input type="hidden" asp-for="IdPropiedad" value="@Model.IdPropiedad" />
                <input type="submit" value="Firmar contrato" class="btn btn-primary" /> |
                <a class="btn btn-primary" asp-action="Index">Volver a la lista</a>
            </div>
        </form>
</div>

<div>  
   @* <a asp-action="Alquilar" asp-route-id="@Model.IdPropiedad">Firmar contrato</a> |*@
    @*<a class="btn btn-primary" asp-action="Index">Volver a la lista</a>*@
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Views/PropiedadAlquiler/Create.cshtml
@model PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadAlquiler

@{
    ViewData["Title"] = "Create";
}

<h1>Agregar</h1>

<h4>Propiedad en Alquiler</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-action="Create" asp-controller="PropiedadAlquiler">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CantMeses" class="control-label"></label>
                <input asp-for="CantMeses" class="form-control" />
                <span asp-validation-for="CantMeses" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FotoPropiedad" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="FotoPropiedad" class="custom-file-input" id="customFile" type="file">
                    <label class="custom-file-label" for="customInput">Seleccione</label>
                </div>
                <span asp-validation-for="FotoPropiedad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <select asp-for="Tipo" class="form-control" asp-items="Html.GetEnumSelectList<TipoPropiedad>()">
                    <option selected="selected" value="">Seleccione</option>
                </select>
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Views/PropiedadAlquiler/Delete.cshtml
@model PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadAlquiler

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar</h1>

<h2>¿Está seguro que quiere borrar esto?</h2>
<br />
<div>
    <h4>Propiedad en Alquiler</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CantMeses)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CantMeses)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dd class="card" style="width: 18rem;">
            <img class="img-fluid img-thumbnail" src="@Model.FotoPropiedadUrl" />
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdPropiedad" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver a la lista</a>
    </form>
</div>

PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Views/PropiedadAlquiler/Details.cshtml
@model PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadAlquiler

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Propiedad en Alquiler</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CantMeses)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CantMeses)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>

        <dt class="col-sm-10" hidden="@(Model.usuario == null)">
            @(Model.Contrato())
            <br/>
        </dt>
        <dd class="card" style="width: 18rem;">
            <img class="img-fluid img-thumbnail" src="@Model.FotoPropiedadUrl" />
        </dd>

    </dl>
        </div>
    <div>
        <a class="btn btn-primary" asp-action="Alquilar" asp-route-id="@Model.IdPropiedad" hidden="@(Model.usuario != null)">Alquilar</a> |
        <a class="btn btn-primary" asp-action="Index">Volver a la lista</a>
    </div>

PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Views/PropiedadAlquiler/Edit.cshtml
@model PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadAlquiler

@{
    ViewData["Title"] = "Edit";
}

<h1>Modificar</h1>

<h4>Propiedad en Alquiler</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-action="Edit" asp-controller="PropiedadAlquiler">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CantMeses" class="control-label"></label>
                <input asp-for="CantMeses" class="form-control" />
                <span asp-validation-for="CantMeses" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="IdPropiedad" />
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FotoPropiedad" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="FotoPropiedad" class="custom-file-input" id="customFile" type="file">
                    <label class="custom-file-label" for="customInput">Seleccione</label>
                </div>
                <span asp-validation-for="FotoPropiedad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <select asp-for="Tipo" class="form-control" asp-items="Html.GetEnumSelectList<TipoPropiedad>()">
                    <option selected="selected" value="">Seleccione</option>
                </select>
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Views/PropiedadAlquiler/Index.cshtml
@model IEnumerable<PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadAlquiler>

@{
    ViewData["Title"] = "Index";
}

<h1>Propiedades en Alquiler</h1>

<p>
    <a asp-action="Create">Agregar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CantMeses)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.SrcImagen)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CantMeses)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.SrcImagen)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Tipo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdPropiedad">Modificar</a> |
                <a asp-action="Details" asp-route-id="@item.IdPropiedad">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.IdPropiedad">Borrar</a> |
                <a asp-action="Alquilar" asp-route-id="@item.IdPropiedad" hidden="@(item.usuario!=null)">Alquilar</a>
            </td>
        </tr>
}
    </tbody>
</table>