PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Models/PropiedadVenta.cs
using System;


namespace PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB
{
    public class PropiedadVenta : Propiedad
    {
        public override string Contrato()
        {
            if (usuario != null)
            {
                return "La persona " + usuario.Nombre + " " + usuario.Apellido + " con E-mail: " + usuario.Email + " ha comprado esta propiedad";
            }
            else
            {
                return "";
            }
        }
    }
}

PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Controllers/PropiedadVentaController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.Context;
using PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.Models;

namespace PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.Controllers
{
    public class PropiedadVentaController : Controller
    {
        private readonly InmobiliariaDatabaseContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PropiedadVentaController(InmobiliariaDatabaseContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: PropiedadVenta
        public async Task<IActionResult> Index()
        {
            return base.View(await _context.PropiedadVenta.Include(x => x.usuario).ToListAsync());
        }

        // GET: PropiedadVenta/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var propiedadVenta = await _context.PropiedadVenta.Include(x => x.usuario)
                .FirstOrDefaultAsync(m => m.IdPropiedad == id);
            if (propiedadVenta == null)
            {
                return NotFound();
            }

            return View(propiedadVenta);
        }

        // GET: PropiedadVenta/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PropiedadVenta/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPropiedad,Descripcion,Precio,FotoPropiedad,Tipo")] PropiedadVenta propiedadVenta)
        {
            if (ModelState.IsValid)
            {
                if (propiedadVenta.FotoPropiedad != null)
                {
                    string folder = "images/prop_venta/";
                    folder += Guid.NewGuid().ToString() + "_" + propiedadVenta.FotoPropiedad.FileName;

                    propiedadVenta.FotoPropiedadUrl = "/" + folder;

                    string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);

                    await propiedadVenta.FotoPropiedad.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                }
                _context.Add(propiedadVenta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(propiedadVenta);
        }

        // GET: PropiedadVenta/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var propiedadVenta = await _context.PropiedadVenta.FindAsync(id);
            if (propiedadVenta == null)
            {
                return NotFound();
            }
            return View(propiedadVenta);
        }

        // POST: PropiedadVenta/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPropiedad,Descripcion,Precio,FotoPropiedad,Tipo")] PropiedadVenta propiedadVenta)
        {
            if (id != propiedadVenta.IdPropiedad)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (propiedadVenta.FotoPropiedad != null)
                    {
                        string folder = "images/prop_alquiler/";
                        folder += Guid.NewGuid().ToString() + "_" + propiedadVenta.FotoPropiedad.FileName;

                        propiedadVenta.FotoPropiedadUrl = "/" + folder;

                        string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);

                        await propiedadVenta.FotoPropiedad.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                    }
                    _context.Update(propiedadVenta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PropiedadVentaExists(propiedadVenta.IdPropiedad))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(propiedadVenta);
        }

        // GET: PropiedadVenta/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var propiedadVenta = await _context.PropiedadVenta
                .FirstOrDefaultAsync(m => m.IdPropiedad == id);
            if (propiedadVenta == null)
            {
                return NotFound();
            }

            return View(propiedadVenta);
        }

        // POST: PropiedadVenta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var propiedadVenta = await _context.PropiedadVenta.FindAsync(id);
            _context.PropiedadVenta.Remove(propiedadVenta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PropiedadVentaExists(int id)
        {
            return _context.PropiedadVenta.Any(e => e.IdPropiedad == id);
        }
    

        // GET: PropiedadAlquiler/Comprar/5
        public async Task<IActionResult> Comprar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.ListaUsuarios = await _context.Usuarios.ToListAsync();

            var propiedadVenta = await _context.PropiedadVenta.FindAsync(id);
            if (propiedadVenta == null)
            {
                return NotFound();
            }
            return View(propiedadVenta);
        }

        // POST: PropiedadAlquiler/Alquilar/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Comprar(PropiedadVenta model)
        {
            PropiedadVenta propiedadVenta = _context.PropiedadVenta.SingleOrDefault(b => b.IdPropiedad == model.IdPropiedad);

            if (propiedadVenta == null)
            {
                return NotFound();
            }

            Usuario usuarioDB = _context.Usuarios.SingleOrDefault(b => b.IdUsuario == model.usuario.IdUsuario);

            if (usuarioDB == null)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            //{
            try
            {
                propiedadVenta.usuario = usuarioDB;
                _context.Update(propiedadVenta);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PropiedadVentaExists(propiedadVenta.IdPropiedad))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return View("Details", propiedadVenta);
        }
    }
}

PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Views/PropiedadVenta/Comprar.cshtml
@model PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadVenta

@{
    ViewData["Title"] = "Comprar";
}

<div>
    <h4>Propiedad a Comprar</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dd class="card" style="width: 18rem;">
            <img class="img-fluid img-thumbnail" src="@Model.FotoPropiedadUrl" />
        </dd>
       
    </dl>
</div>

<div class="col-md-4">   
        <form method="post" enctype="multipart/form-data" asp-action="Comprar" asp-controller="PropiedadVenta">

            <div class="row">
                <div class="col-sm-2">
                    @Html.DisplayNameFor(model => model.usuario)
                </div>
                <select asp-for="usuario.IdUsuario" class="form-control" asp-items="@(new SelectList(ViewBag.ListaUsuarios,"IdUsuario", "Nombre"))">
                    <option selected="selected" value="">Seleccione</option>
                </select>
            </div>
            <br>
            <div class="row">
                <input type="hidden" asp-for="IdPropiedad" value="@Model.IdPropiedad" />
                <input type="submit" value="Firmar contrato" class="btn btn-primary" /> |
                <a class="btn btn-primary" asp-action="Index">Volver a la lista</a>
            </div>
        </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Views/PropiedadVenta/Create.cshtml
@model PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadVenta

@{
    ViewData["Title"] = "Create";
}

<h1>Agregar</h1>

<h4>Propiedad en Venta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-action="Create" asp-controller="PropiedadVenta">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FotoPropiedad" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="FotoPropiedad" class="custom-file-input" id="customFile" type="file">
                    <label class="custom-file-label" for="customInput">Seleccione</label>
                </div>
                <span asp-validation-for="FotoPropiedad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <select asp-for="Tipo" class="form-control" asp-items="Html.GetEnumSelectList<TipoPropiedad>()">
                    <option selected="selected" value="">Seleccione</option>
                </select>
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Views/PropiedadVenta/Delete.cshtml
@model PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadVenta

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar</h1>

<h2>¿Está seguro que quiere borrarlo?</h2>
<br />
<div>
    <h4>Propiedad en Venta</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dd class="card" style="width: 18rem;">
            <img class="img-fluid img-thumbnail" src="@Model.FotoPropiedadUrl" />
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdPropiedad" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver a la lista</a>
    </form>
</div>

PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Views/PropiedadVenta/Details.cshtml
@model PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadVenta

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Propiedad en Venta</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>

        <dt class="col-sm-10" hidden="@(Model.usuario == null)">
            @(Model.Contrato())
            <br/>
        </dt>
        
        <div class="card" style="width: 18rem;">
            <img class="img-fluid img-thumbnail" src="@Model.FotoPropiedadUrl" />
        </div>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-action="Comprar" asp-route-id="@Model.IdPropiedad" hidden="@(Model.usuario != null)">Comprar</a> |
    <a asp-action="Index">Volver a la lista</a>
</div>

PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Views/PropiedadVenta/Edit.cshtml
@model PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadVenta

@{
    ViewData["Title"] = "Edit";
}

<h1>Modificar</h1>

<h4>Propiedad en Venta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-action="Edit" asp-controller="PropiedadVenta">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdPropiedad" />
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FotoPropiedad" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="FotoPropiedad" class="custom-file-input" id="customFile" type="file">
                    <label class="custom-file-label" for="customInput">Seleccione</label>
                </div>
                <span asp-validation-for="FotoPropiedad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <select asp-for="Tipo" class="form-control" asp-items="Html.GetEnumSelectList<TipoPropiedad>()">
                    <option selected="selected" value="">Seleccione</option>
                </select>
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB/Views/PropiedadVenta/Index.cshtml
@model IEnumerable<PNT1_GRUPO6_PROYECTO_INMOBILIARIA_WEB.PropiedadVenta>

@{
    ViewData["Title"] = "Index";
}

<h1>Propiedades en Venta</h1>

<p>
    <a asp-action="Create">Agregar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.SrcImagen)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.SrcImagen)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Tipo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdPropiedad">Modificar</a> |
                <a asp-action="Details" asp-route-id="@item.IdPropiedad">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.IdPropiedad">Borrar</a> |
                <a asp-action="Comprar" asp-route-id="@item.IdPropiedad"hidden="@(item.usuario!=null)">Comprar</a>
            </td>
        </tr>
}
    </tbody>
</table>